var topics =
[
    [ "Main", "group__main.html", "group__main" ],
    [ "Synchronization", "group__main__sync.html", null ],
    [ "Memory", "group__main__memory.html", null ],
    [ "Maths", "group__main__maths.html", null ],
    [ "Debug console", "group__main__debug.html", null ],
    [ "Miscellaneous", "group__main__misc.html", null ],
    [ "Drawing", "group__drawing.html", "group__drawing" ],
    [ "General", "group__drawing__general.html", null ],
    [ "Colors", "group__drawing__color.html", null ],
    [ "Shapes", "group__drawing__shapes.html", null ],
    [ "Advanced", "group__drawing__adv.html", null ],
    [ "Images", "group__image.html", null ],
    [ "Creating or loading images", "group__image__creation.html", null ],
    [ "Drawing images", "group__image__drawing.html", null ],
    [ "Image placement", "group__image__placement.html", null ],
    [ "Image manipulation", "group__image__manip.html", null ],
    [ "Simili sprite system", "group__image__sprites.html", null ],
    [ "Image palettes", "group__image__palette.html", null ],
    [ "Pixel access", "group__image__pixel.html", null ],
    [ "Drawbuffers", "group__image__drawbuf.html", null ],
    [ "Advanced", "group__image__adv.html", null ],
    [ "Audio", "group__audio.html", null ],
    [ "General", "group__audio__general.html", null ],
    [ "Loading", "group__audio__load.html", null ],
    [ "Player", "group__audio__play.html", null ],
    [ "Advanced", "group__audio__adv.html", null ],
    [ "Controller", "group__keys.html", null ],
    [ "USB", "group___usb.html", "group___usb" ],
    [ "Dialogs", "group___dialogs.html", null ],
    [ "On-Screen Keyboard", "group___o_s_k.html", null ],
    [ "Save and Load", "group__saveload.html", null ],
    [ "Network", "group___network.html", null ],
    [ "Browser", "group___browser.html", null ],
    [ "AdHoc", "group___ad_hoc.html", null ],
    [ "Maps", "group__maps.html", null ],
    [ "Message boxes", "group__msgbox.html", null ],
    [ "Text functions", "group__text.html", null ],
    [ "SFont", "group___s_font.html", null ],
    [ "Math", "group__math.html", "group__math" ],
    [ "code conversion (ccc)", "group___character.html", null ],
    [ "Virtual Files", "group__virtualfile.html", null ],
    [ "I/O routines", "group__virtualfile__io.html", null ],
    [ "Virtual file sources", "group__virtualfile__sources.html", null ],
    [ "RAM virtual files", "group__virtualfile__ram.html", null ]
];